### ISSUE TITLE
hmstr и kzt

### ISSUE THREAD

**Issue by KolxozGG** [onlive1337/OTC#3]
Бот не реагирует на **KZT** и **HMSTR**, пофиксите пожалуйста.

**Comment by onlive1337** [comment]
@KolxozGG я твой рот выебу

**Comment by onlive1337** [comment]
KZT пока не знаю, HMSTR чуть позже добавлю

**Comment by onlive1337** [comment]
Добавил HMSTR

**Comment by onlive1337** [comment]
Всё, пофиксил
